name: GitHub pages Deploy

on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: install packages
        run: npm install
        
      - name: build Gatsby
        env:
          GH_API_KEY: ${{ secrets.API_KEY }} 
        run: npm run bulid

      - name: deploy with gh-pages
        uses: maxheld83/ghpages@v0.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_PAT: ${{ secrets.API_KEY }}
          BUILD_DIR: 'public/'
